#!/usr/bin/env python3
"""Writes src/physics/watereos.js: water's density from IAPWS-95, tabulated.

    pip install --target=/tmp/pydeps iapws
    PYTHONPATH=/tmp/pydeps python3 tools/watereos.py

The model never needed water's density at anything but ocean temperatures until
the cross-section started drawing the boundary under a lid, which runs from
1500 °C supercritical fluid down to 40 °C liquid. A cold-liquid law put 100 bar
of weight in a layer whose hot half is a tenth as dense as that.

Two tables of log10(density), both on a grid of temperature against
x = log10(P / psat(T)) -- pressure measured from the boiling curve rather than
from zero. On that grid the saturation line is a grid line, x = 0, so a liquid
query never interpolates against a steam value and the reverse (on a plain
pressure grid the cells that straddle boiling were 16% out). Above the critical
temperature psat is held at the critical pressure and the grid is plain
pressure again, continuous across T_crit because psat(T_crit) = P_crit.

Densities are solved here from the IAPWS-95 Helmholtz equation directly, by
bisection on the stable branch (the library's own P,T solver fails in parts of
the steam region). Accuracy of the interpolated table against IAPWS-95, 8000
random points over 273-4000 K and 100 Pa-10 GPa: liquid and steam within 0.8%,
supercritical within 1.4% (p99) and 4% at worst, the worst within 20 K of the
critical point. IAPWS-95 is fitted to 1273 K and 1 GPa; above that it is the
formulation's own extrapolation, which the release describes as reasonable.
"""
import math, os
from iapws.iapws95 import IAPWS95, _phird

C = IAPWS95._constants
TC, RC, PC = 647.096, 322.0, 22.064e6
RS = C['R'] / 18.015268 * 1000


def p_of(rho, T):
    return rho * RS * T * (1 + (rho / RC) * _phird(TC / T, rho / RC, C))


def psat(T):
    return IAPWS95._Vapor_Pressure(T) * 1e6


def solve(T, P, lo, hi):
    a, b = math.log(lo), math.log(hi)
    for _ in range(80):
        m = 0.5 * (a + b)
        if p_of(math.exp(m), T) < P:
            a = m
        else:
            b = m
    return math.exp(0.5 * (a + b))


def rho(T, P, phase):
    if T >= TC:
        return solve(T, P, 1e-12, 3500)
    ps = psat(T)
    rl, rv = IAPWS95._Liquid_Density(T), IAPWS95._Vapor_Density(T)
    if phase == 'l':
        return rl if P <= ps else solve(T, P, rl * 0.999, 3500)
    return rv if P >= ps else solve(T, P, 1e-12, rv * 1.001)


def lps(T):
    return math.log10(psat(T)) if T < TC else math.log10(PC)


TL = [273.16] + [280 + 10 * i for i in range(35)] + [625, 630, 635, 640, 643, 645, 646, TC]
TG = TL + [648, 650, 653, 657, 662, 670, 680, 688, 695, 702, 710, 720, 730, 740, 750, 762,
           775, 787, 800, 825, 850, 900, 950, 1000, 1100, 1200, 1350, 1500, 1700, 2000,
           2400, 2900, 3500, 4000]
XL = [0, 0.01, 0.03, 0.06, 0.1, 0.15, 0.2, 0.3, 0.45, 0.6, 0.8, 1, 1.25, 1.5, 1.75, 2, 2.5,
      3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.3]
XG = [-8, -7, -6, -5, -4, -3, -2.5, -2, -1.5, -1.2, -0.9, -0.7, -0.5, -0.35, -0.25, -0.15,
      -0.1, -0.06, -0.03, -0.01, 0, 0.01, 0.03, 0.06, 0.1, 0.15, 0.2, 0.25, 0.3, 0.37, 0.45,
      0.52, 0.6, 0.7, 0.8, 0.9, 1, 1.25, 1.5, 1.75, 2, 2.35, 2.7]


def table(Ts, Xs, phase):
    return [[math.log10(rho(T, 10 ** (lps(T) + x), phase)) for x in Xs] for T in Ts]


def js_rows(tab):
    return ',\n'.join('  [' + ','.join(f'{v:.4f}' for v in row) + ']' for row in tab)


def js_list(xs):
    return '[' + ','.join(f'{x:g}' for x in xs) + ']'


# Reference points for the self-test, straight from the equation of state.
REF = [(298.15, 1e5, 'l'), (373.15, 1.1e5, 'l'), (573.15, 1e7, 'l'), (640, 4.3e7, 'l'),
       (308, 1e8, 'l'), (600, 5e6, 'g'), (650, 1.5e7, 'g'), (673.15, 2.5e7, 'g'),
       (773.15, 2.5e7, 'g'), (900, 1e8, 'g'), (1258, 5.6e7, 'g'), (1787, 2.55e8, 'g')]

if __name__ == '__main__':
    L, G = table(TL, XL, 'l'), table(TG, XG, 'g')
    ref = ',\n'.join(f"  [{T:g}, {P:g}, '{'liquid' if ph == 'l' else 'fluid'}', {rho(T, P, ph):.2f}]"
                     for T, P, ph in REF)
    out = f"""// GENERATED by tools/watereos.py from IAPWS-95 -- do not edit by hand.
//
// log10 of water's density (kg/m^3) against temperature (K) and
// x = log10(P / psat(T)), psat held at the critical pressure above T_crit.
// LIQUID covers x >= 0 below the critical temperature; FLUID covers steam
// (x <= 0) below it and every pressure above it. Cells past the boiling curve
// hold the saturated value, so a clamped query reads the phase boundary.
export const EOS_T_LIQUID = {js_list(TL)};
export const EOS_T_FLUID = {js_list(TG)};
export const EOS_X_LIQUID = {js_list(XL)};
export const EOS_X_FLUID = {js_list(XG)};
export const EOS_LIQUID = [
{js_rows(L)}
];
export const EOS_FLUID = [
{js_rows(G)}
];
// [T (K), P (Pa), phase, IAPWS-95 density] -- what the self-test holds it to.
export const EOS_REFERENCE = [
{ref}
];
"""
    path = os.path.join(os.path.dirname(__file__), '..', 'src', 'physics', 'watereos-table.js')
    with open(path, 'w') as f:
        f.write(out)
    print('wrote', path, len(out), 'bytes')
